services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: flowmind-postgres

    environment:
      POSTGRES_USER: flowmind
      POSTGRES_PASSWORD: flowmind123
      POSTGRES_DB: flowmind_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: